In [2]:
import pandas as pd
import numpy as np

In [3]:
retail = pd.read_csv("../data/raw/retail_price.csv")
online = pd.read_csv("../data/raw/online_retail_II.csv")

In [4]:
print("Retail:", retail.shape)
print("Online:", online.shape)

Retail: (676, 30)
Online: (1067371, 8)

In [5]:
retail["month_year"] = pd.to_datetime(
    retail["month_year"],
    format="%d-%m-%Y"
)

In [6]:
retail.isnull().sum()

product_id                    0
product_category_name         0
month_year                    0
qty                           0
total_price                   0
freight_price                 0
unit_price                    0
product_name_lenght           0
product_description_lenght    0
product_photos_qty            0
product_weight_g              0
product_score                 0
customers                     0
weekday                       0
weekend                       0
holiday                       0
month                         0
year                          0
s                             0
volume                        0
comp_1                        0
ps1                           0
fp1                           0
comp_2                        0
ps2                           0
fp2                           0
comp_3                        0
ps3                           0
fp3                           0
lag_price                     0
dtype: int64

In [7]:
retail = retail.sort_values(
    ["product_id", "month_year"]
).reset_index(drop=True)

In [8]:
print(retail["month_year"].min())
print(retail["month_year"].max())

2017-01-01 00:00:00
2018-08-01 00:00:00

In [9]:
retail["calculated_total"] = (
    retail["qty"] * retail["unit_price"]
)

In [10]:
retail["price_difference"] = (
    retail["total_price"] - retail["calculated_total"]
)

print(retail["price_difference"].describe())

count    676.000000
mean       0.488275
std        8.115285
min      -44.290909
25%        0.000000
50%        0.000000
75%        0.000000
max      147.551064
Name: price_difference, dtype: float64

In [11]:
print(
    retail[
        retail["price_difference"].abs() > 0.01
    ][
        ["qty", "unit_price", "total_price",
         "calculated_total", "price_difference"]
    ].head(20)
)

    qty  unit_price  total_price  calculated_total  price_difference
26   18   88.488235      1594.20       1592.788235          1.411765
33   10   77.933333       781.30        779.333333          1.966667
38   11   98.300000      1082.00       1081.300000          0.700000
41    9   90.875000       815.00        817.875000         -2.875000
47   32   44.154444      1421.67       1412.942222          8.727778
59   52  199.509804     10375.00      10374.509803          0.490197
60   32  163.398710      5222.36       5228.758710         -6.398710
62    6  100.900000       611.40        605.400000          6.000000
69   31   90.534000      2795.14       2806.554000        -11.414000
70   30   84.756087      2537.19       2542.682609         -5.492609
71   13   87.500000      1139.80       1137.500000          2.300000
74   18   66.342143      1199.48       1194.158571          5.321429
78   29   97.642500      2831.55       2831.632500         -0.082500
79   71   78.712281      5581.80       5588.571930         -6.771930
80   27   81.023913      2187.30       2187.645652         -0.345652
81   13   80.666667      1042.90       1048.666667         -5.766667
82   11   79.800000       876.90        877.800000         -0.900000
86   15  178.057143      2715.70       2670.857143         44.842856
87   15  149.852500      2247.72       2247.787500         -0.067500
88    4  146.600000       584.77        586.400000         -1.630000

In [12]:
print("Negative quantities:",
      (online["Quantity"] < 0).sum())

print("Zero quantities:",
      (online["Quantity"] == 0).sum())

print("Negative prices:",
      (online["Price"] < 0).sum())

print("Zero prices:",
      (online["Price"] == 0).sum())

Negative quantities: 22950
Zero quantities: 0
Negative prices: 5
Zero prices: 6202

In [13]:
print(
    online[online["Quantity"] < 0]
    [["Invoice", "StockCode", "Description",
      "Quantity", "InvoiceDate", "Price"]]
    .head(20)
)

     Invoice StockCode                          Description  Quantity  \
178  C489449     22087             PAPER BUNTING WHITE LACE       -12
179  C489449    85206A         CREAM FELT EASTER EGG BASKET        -6
180  C489449     21895        POTTING SHED SOW 'N' GROW SET        -4
181  C489449     21896                   POTTING SHED TWINE        -6
182  C489449     22083           PAPER CHAIN KIT RETRO SPOT       -12
183  C489449     21871                  SAVE THE PLANET MUG       -12
184  C489449     84946      ANTIQUE SILVER TEA GLASS ETCHED       -12
185  C489449    84970S    HANGING HEART ZINC T-LIGHT HOLDER       -24
186  C489449     22090            PAPER BUNTING RETRO SPOTS       -12
196  C489459    90200A           PURPLE SWEETHEART BRACELET        -3
197  C489459    90200D             PINK SWEETHEART BRACELET        -3
198  C489459    90200B            BLACK SWEETHEART BRACELET        -3
199  C489459    90200E            GREEN SWEETHEART BRACELET        -3
200  C489459    90200C             BLUE SWEETHEART BRACELET        -3
201  C489459    90185C       BLACK DIAMANTE EXPANDABLE RING        -3
202  C489459    90185B    AMETHYST DIAMANTE EXPANDABLE RING        -3
203  C489459    90003C  MIDNIGHT BLUE PAIR HEART HAIR SLIDE        -3
204  C489459    90003D       CRYSTAL PAIR HEART HAIR SLIDES        -3
205  C489459    90003B   ROSE COLOUR PAIR HEART HAIR SLIDES        -3
206  C489459    90209C          PINK ENAMEL+GLASS HAIR COMB        -3

             InvoiceDate  Price
178  2009-12-01 10:33:00   2.95
179  2009-12-01 10:33:00   1.65
180  2009-12-01 10:33:00   4.25
181  2009-12-01 10:33:00   2.10
182  2009-12-01 10:33:00   2.95
183  2009-12-01 10:33:00   1.25
184  2009-12-01 10:33:00   1.25
185  2009-12-01 10:33:00   0.85
186  2009-12-01 10:33:00   2.95
196  2009-12-01 10:44:00   4.25
197  2009-12-01 10:44:00   4.25
198  2009-12-01 10:44:00   4.25
199  2009-12-01 10:44:00   4.25
200  2009-12-01 10:44:00   4.25
201  2009-12-01 10:44:00   4.25
202  2009-12-01 10:44:00   4.25
203  2009-12-01 10:44:00   3.75
204  2009-12-01 10:44:00   3.75
205  2009-12-01 10:44:00   3.75
206  2009-12-01 10:44:00   2.10

In [14]:
print(
    online[online["Price"] <= 0]
    [["Invoice", "StockCode", "Description",
      "Quantity", "InvoiceDate", "Price"]]
    .head(20)
)

     Invoice StockCode          Description  Quantity          InvoiceDate  \
263   489464     21733         85123a mixed       -96  2009-12-01 10:52:00
283   489463     71477                short      -240  2009-12-01 10:52:00
284   489467    85123A          21733 mixed      -192  2009-12-01 10:53:00
470   489521     21646                  NaN       -50  2009-12-01 11:44:00
3114  489655     20683                  NaN       -44  2009-12-01 17:26:00
3161  489659     21350                  NaN       230  2009-12-01 17:39:00
3162  489660     35956                 lost     -1043  2009-12-01 17:43:00
3168  489663    35605A              damages      -117  2009-12-01 18:02:00
3731  489781     84292                  NaN        17  2009-12-02 11:45:00
4296  489806     18010                  NaN      -770  2009-12-02 12:42:00
4538  489820     21133      invcd as 84879?      -720  2009-12-02 13:23:00
4566  489821    85049G                  NaN      -240  2009-12-02 13:25:00
4674  489825     22076   6 RIBBONS EMPIRE          12  2009-12-02 13:34:00
5904  489861       DOT       DOTCOM POSTAGE         1  2009-12-02 14:50:00
6378  489882    35751C                  NaN        12  2009-12-02 16:22:00
6555  489898    79323G                  NaN       954  2009-12-03 09:40:00
6556  489899   79323GR         sold as gold      -954  2009-12-03 09:41:00
6576  489901     21098                  NaN      -200  2009-12-03 09:47:00
6581  489903     21166                  NaN        48  2009-12-03 09:57:00
6781  489998     48185  DOOR MAT FAIRY CAKE         2  2009-12-03 11:19:00

      Price
263     0.0
283     0.0
284     0.0
470     0.0
3114    0.0
3161    0.0
3162    0.0
3168    0.0
3731    0.0
4296    0.0
4538    0.0
4566    0.0
4674    0.0
5904    0.0
6378    0.0
6555    0.0
6556    0.0
6576    0.0
6581    0.0
6781    0.0

In [15]:
online["InvoiceDate"] = pd.to_datetime(
    online["InvoiceDate"]
)

In [16]:
print(online["InvoiceDate"].min())
print(online["InvoiceDate"].max())

2009-12-01 07:45:00
2011-12-09 12:50:00

In [17]:
# Check cancellation invoices

cancelled_invoices = online["Invoice"].astype(str).str.startswith("C")

print("Cancellation invoices:", cancelled_invoices.sum())
print("Total transactions:", len(online))

Cancellation invoices: 19494
Total transactions: 1067371

In [18]:
# Compare negative quantities with cancellation invoices

print(
    pd.crosstab(
        cancelled_invoices,
        online["Quantity"] < 0
    )
)

Quantity    False  True
Invoice
False     1044420   3457
True            1  19493

In [19]:
negative_price = online[online["Price"] < 0]

print("Negative price records:")
display(
    negative_price[
        ["Invoice", "StockCode", "Description",
         "Quantity", "InvoiceDate", "Price"]
    ]
)

Negative price records:

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price
179403,A506401,B,Adjust bad debt,1,2010-04-29 13:36:00,-53594.36
276274,A516228,B,Adjust bad debt,1,2010-07-19 11:24:00,-44031.79
403472,A528059,B,Adjust bad debt,1,2010-10-20 12:04:00,-38925.87
825444,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06
825445,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06

In [20]:
zero_price = online[online["Price"] == 0]

print("Zero-price transactions:", len(zero_price))

display(
    zero_price[
        ["Invoice", "StockCode", "Description",
         "Quantity", "InvoiceDate", "Price"]
    ].head(30)
)

Zero-price transactions: 6202

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.0
283,489463,71477,short,-240,2009-12-01 10:52:00,0.0
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.0
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.0
3114,489655,20683,NaN,-44,2009-12-01 17:26:00,0.0
3161,489659,21350,NaN,230,2009-12-01 17:39:00,0.0
3162,489660,35956,lost,-1043,2009-12-01 17:43:00,0.0
3168,489663,35605A,damages,-117,2009-12-01 18:02:00,0.0
3731,489781,84292,NaN,17,2009-12-02 11:45:00,0.0
4296,489806,18010,NaN,-770,2009-12-02 12:42:00,0.0
4538,489820,21133,invcd as 84879?,-720,2009-12-02 13:23:00,0.0
4566,489821,85049G,NaN,-240,2009-12-02 13:25:00,0.0
4674,489825,22076,6 RIBBONS EMPIRE,12,2009-12-02 13:34:00,0.0
5904,489861,DOT,DOTCOM POSTAGE,1,2009-12-02 14:50:00,0.0
6378,489882,35751C,NaN,12,2009-12-02 16:22:00,0.0
6555,489898,79323G,NaN,954,2009-12-03 09:40:00,0.0
6556,489899,79323GR,sold as gold,-954,2009-12-03 09:41:00,0.0
6576,489901,21098,NaN,-200,2009-12-03 09:47:00,0.0
6581,489903,21166,NaN,48,2009-12-03 09:57:00,0.0
6781,489998,48185,DOOR MAT FAIRY CAKE,2,2009-12-03 11:19:00,0.0
6911,490007,84347,21494,-720,2009-12-03 12:09:00,0.0
7204,490015,21982,NaN,467,2009-12-03 12:29:00,0.0
7205,490016,21982,NaN,-1012,2009-12-03 12:30:00,0.0
7559,490055,20620,NaN,-25,2009-12-03 13:22:00,0.0
8553,490084,85064,NaN,-89,2009-12-03 15:37:00,0.0
9249,490123,84508B,NaN,184,2009-12-03 18:08:00,0.0
9308,490130,21493,lost?,-600,2009-12-03 18:28:00,0.0
9667,490146,21558,NaN,-169,2009-12-04 09:29:00,0.0
10236,490150,84347,NaN,80,2009-12-04 09:44:00,0.0
10508,490165,21493,NaN,-106,2009-12-04 11:32:00,0.0

In [21]:
online["is_cancelled"] = (
    online["Invoice"]
    .astype(str)
    .str.startswith("C")
)

print(
    online.groupby("is_cancelled")["Quantity"]
    .agg(["count", "min", "max", "mean"])
)

                count    min    max       mean
is_cancelled
False         1047877  -9600  80995  10.592354
True            19494 -80995      1 -25.186827

In [22]:
non_cancelled_negative = online[
    (~online["is_cancelled"]) &
    (online["Quantity"] < 0)
]

print("Negative quantity but non-cancellation:",
      len(non_cancelled_negative))

display(
    non_cancelled_negative[
        ["Invoice", "StockCode", "Description",
         "Quantity", "InvoiceDate", "Price"]
    ].head(50)
)

Negative quantity but non-cancellation: 3457

      Invoice StockCode      Description  Quantity         InvoiceDate  Price
263    489464     21733     85123a mixed       -96 2009-12-01 10:52:00    0.0
283    489463     71477            short      -240 2009-12-01 10:52:00    0.0
284    489467    85123A      21733 mixed      -192 2009-12-01 10:53:00    0.0
470    489521     21646              NaN       -50 2009-12-01 11:44:00    0.0
3114   489655     20683              NaN       -44 2009-12-01 17:26:00    0.0
3162   489660     35956             lost     -1043 2009-12-01 17:43:00    0.0
3168   489663    35605A          damages      -117 2009-12-01 18:02:00    0.0
4296   489806     18010              NaN      -770 2009-12-02 12:42:00    0.0
4538   489820     21133  invcd as 84879?      -720 2009-12-02 13:23:00    0.0
4566   489821    85049G              NaN      -240 2009-12-02 13:25:00    0.0
6556   489899   79323GR     sold as gold      -954 2009-12-03 09:41:00    0.0
6576   489901     21098              NaN      -200 2009-12-03 09:47:00    0.0
6911   490007     84347            21494      -720 2009-12-03 12:09:00    0.0
7205   490016     21982              NaN     -1012 2009-12-03 12:30:00    0.0
7559   490055     20620              NaN       -25 2009-12-03 13:22:00    0.0
8553   490084     85064              NaN       -89 2009-12-03 15:37:00    0.0
9308   490130     21493            lost?      -600 2009-12-03 18:28:00    0.0
9667   490146     21558              NaN      -169 2009-12-04 09:29:00    0.0
10508  490165     21493              NaN      -106 2009-12-04 11:32:00    0.0
11973  490354     21489              NaN       -23 2009-12-04 16:39:00    0.0
12237  490379     21490              NaN       -44 2009-12-05 13:26:00    0.0
12299  490384     84721              NaN       -42 2009-12-05 14:00:00    0.0
14480  490540     37446              NaN      -725 2009-12-07 09:24:00    0.0
15883  490713     84347              NaN       -20 2009-12-07 15:26:00    0.0
15908  490715     22158              NaN       -30 2009-12-07 15:27:00    0.0
16185  490735    35976B              NaN       -60 2009-12-07 17:12:00    0.0
16186  490736     35983              NaN      -200 2009-12-07 17:13:00    0.0
17427  490765     21450          damaged       -31 2009-12-08 10:59:00    0.0
17428  490766     51008              wet      -200 2009-12-08 11:06:00    0.0
19312  490975    15059A              NaN      -126 2009-12-08 16:41:00    0.0
19313  490976     84571              NaN      -120 2009-12-08 16:42:00    0.0
20759  491046     20987              NaN      -100 2009-12-09 10:03:00    0.0
20760  491047     21982              NaN       -50 2009-12-09 10:04:00    0.0
20970  491065     84855              MIA      -108 2009-12-09 11:59:00    0.0
20975  491066     35949              NaN       -67 2009-12-09 12:17:00    0.0
21646  491108     84922              NaN      -360 2009-12-09 14:29:00    0.0
22088  491128     21490              NaN       -20 2009-12-09 16:00:00    0.0
22116  491137     21489              NaN        -8 2009-12-09 16:25:00    0.0
22133  491141     22174              NaN       -58 2009-12-09 16:43:00    0.0
22854  491167    17013A              NaN       -45 2009-12-10 11:09:00    0.0
23542  491206     84841              NaN       -54 2009-12-10 14:10:00    0.0
23988  491355    17014C              NaN       -96 2009-12-10 15:52:00    0.0
24941  491451     20940              NaN       -46 2009-12-11 11:09:00    0.0
26004  491638     21353              NaN      -136 2009-12-11 15:59:00    0.0
26005  491639     20668              NaN     -1395 2009-12-11 16:02:00    0.0
28111  491732    79030A          smashed      -350 2009-12-14 10:00:00    0.0
29109  491817     72487              NaN      -322 2009-12-14 13:37:00    0.0
32104  491972     21100      bad quality       -76 2009-12-14 18:43:00    0.0
32105  491974    72752B              NaN       -21 2009-12-14 18:44:00    0.0
32106  491975    72752C              NaN       -24 2009-12-14 18:44:00    0.0

In [23]:
zero_price_summary = (
    online[online["Price"] == 0]
    ["Description"]
    .value_counts(dropna=False)
    .head(30)
)

display(zero_price_summary)

Description
NaN                                    4382
check                                   162
?                                        92
damages                                  84
damaged                                  81
found                                    28
missing                                  27
sold as set on dotcom                    20
Damaged                                  17
adjustment                               16
OWL DOORSTOP                             15
POLYESTER FILLER PAD 45x45cm             12
dotcom                                   12
amazon                                   11
FRENCH BLUE METAL DOOR SIGN 1            10
IVORY KITCHEN SCALES                     10
POLYESTER FILLER PAD 40x40cm             10
AIRLINE BAG VINTAGE WORLD CHAMPION        9
smashed                                   9
RED KITCHEN SCALES                        9
BOX OF 24 COCKTAIL PARASOLS               9
FRENCH BLUE METAL DOOR SIGN 8             9
Unsaleable, destroyed.                    9
Found                                     9
PICNIC BASKET WICKER LARGE                9
thrown away                               9
FRENCH BLUE METAL DOOR SIGN 4             8
FRENCH BLUE METAL DOOR SIGN No            8
CHILDS GARDEN SPADE BLUE                  8
RECIPE BOX PANTRY YELLOW DESIGN           8
Name: count, dtype: int64

In [24]:
print("Missing Customer ID:",
      online["Customer ID"].isnull().sum())

print("Missing Customer ID percentage:",
      online["Customer ID"].isnull().mean() * 100)

Missing Customer ID: 243007
Missing Customer ID percentage: 22.766872999172733

In [25]:
print("Missing Description:",
      online["Description"].isnull().sum())

print("Missing Description percentage:",
      online["Description"].isnull().mean() * 100)

Missing Description: 4382
Missing Description percentage: 0.4105414143723223

In [26]:
online_clean = online.copy()
print("Original rows:", len(online))

Original rows: 1067371

In [27]:
online_clean = online_clean[
    online_clean["is_cancelled"] == False
]

print("After removing cancellations:", len(online_clean))

After removing cancellations: 1047877

In [28]:
online_clean = online_clean[
    online_clean["Quantity"] > 0
]

print("After removing non-positive quantities:", len(online_clean))

After removing non-positive quantities: 1044420

In [30]:
online_clean = online_clean[
    online_clean["Price"] > 0
]

print("After removing non-positive prices:", len(online_clean))

After removing non-positive prices: 1041670

In [34]:
print("Final shape:", online_clean.shape)

print("Negative quantities:",
      (online_clean["Quantity"] < 0).sum())

print("Zero quantities:",
      (online_clean["Quantity"] == 0).sum())

print("Negative prices:",
      (online_clean["Price"] < 0).sum())

print("Zero prices:",
      (online_clean["Price"] == 0).sum())

Final shape: (1041670, 8)
Negative quantities: 0
Zero quantities: 0
Negative prices: 0
Zero prices: 0

In [35]:
# Check duplicate rows
duplicate_count = online_clean.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 33757

In [36]:
duplicate_count = online_clean.duplicated().sum()
print("Duplicate rows:", duplicate_count)

Duplicate rows: 33757

In [37]:
# Check some duplicate rows
duplicates = online_clean[
    online_clean.duplicated(keep=False)
].sort_values(
    ["Invoice", "StockCode", "InvoiceDate"]
)

print("Total rows involved in duplicates:", len(duplicates))

Total rows involved in duplicates: 66094

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
669,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
721,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
723,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
716,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
725,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
784,489536,17164D,ASS COL SMALL SAND FROG P'WEIGHT,1,2009-12-01 12:13:00,0.42,16393.0,United Kingdom
808,489536,17164D,ASS COL SMALL SAND FROG P'WEIGHT,1,2009-12-01 12:13:00,0.42,16393.0,United Kingdom
772,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom
856,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom
826,489536,21231,SWEETHEART CERAMIC TRINKET BOX,1,2009-12-01 12:13:00,1.25,16393.0,United Kingdom

In [38]:
display(duplicates.head(30))

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
379,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
391,489517,21491,SET OF THREE VINTAGE GIFT WRAPS,1,2009-12-01 11:34:00,1.95,16329.0,United Kingdom
365,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
363,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
394,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
362,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
368,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
367,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
388,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
390,489517,84951A,S/4 PISTACHIO LOVEBIRD COASTERS,1,2009-12-01 11:34:00,2.55,16329.0,United Kingdom
634,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
657,489529,22028,PENNY FARTHING BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
656,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
658,489529,22036,DINOSAUR BIRTHDAY CARD,12,2009-12-01 11:51:00,0.42,17984.0,United Kingdom
628,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
669,489529,48129,DOOR MAT TOPIARY,1,2009-12-01 11:51:00,6.75,17984.0,United Kingdom
721,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
723,489533,22073,RETRO SPOT STORAGE JAR,1,2009-12-01 12:02:00,3.75,16011.0,United Kingdom
716,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
725,489533,84946,ANTIQUE SILVER TEA GLASS ETCHED,6,2009-12-01 12:02:00,1.25,16011.0,United Kingdom
784,489536,17164D,ASS COL SMALL SAND FROG P'WEIGHT,1,2009-12-01 12:13:00,0.42,16393.0,United Kingdom
808,489536,17164D,ASS COL SMALL SAND FROG P'WEIGHT,1,2009-12-01 12:13:00,0.42,16393.0,United Kingdom
772,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom
856,489536,21034,REX CASH+CARRY JUMBO SHOPPER,1,2009-12-01 12:13:00,0.95,16393.0,United Kingdom
826,489536,21231,SWEETHEART CERAMIC TRINKET BOX,1,2009-12-01 12:13:00,1.25,16393.0,United Kingdom

In [39]:
# Remove exact duplicate transactions
before_duplicates = len(online_clean)

online_clean = online_clean.drop_duplicates()

after_duplicates = len(online_clean)

print("Rows before removing duplicates:", before_duplicates)
print("Rows after removing duplicates:", after_duplicates)
print("Duplicate rows removed:", before_duplicates - after_duplicates)

Rows before removing duplicates: 1041670
Rows after removing duplicates: 1007913
Duplicate rows removed: 33757

In [40]:
print("Remaining duplicate rows:",
      online_clean.duplicated().sum())

Remaining duplicate rows: 0

In [41]:
# Check missing values in cleaned dataset

missing_values = online_clean.isnull().sum()

print(missing_values)

Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    228488
Country             0
dtype: int64

In [42]:
# Show missing-value percentages

missing_percentage = (
    online_clean.isnull().mean() * 100
).round(2)

print(missing_percentage)

Invoice         0.00
StockCode       0.00
Description     0.00
Quantity        0.00
InvoiceDate     0.00
Price           0.00
Customer ID    22.67
Country         0.00
dtype: float64

In [43]:
# Check data types
print(online_clean.dtypes)

Invoice                object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
Price                 float64
Customer ID           float64
Country                object
dtype: object

In [44]:
# Check basic dataset information
online_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1007913 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1007913 non-null  object
 1   StockCode    1007913 non-null  object
 2   Description  1007913 non-null  object
 3   Quantity     1007913 non-null  int64
 4   InvoiceDate  1007913 non-null  datetime64[ns]
 5   Price        1007913 non-null  float64
 6   Customer ID  779425 non-null   float64
 7   Country      1007913 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 69.2+ MB

In [46]:
# Check Quantity and Price distribution
print("Quantity statistics:")
print(online_clean["Quantity"].describe())

print("\nPrice statistics:")
print(online_clean["Price"].describe())

Quantity statistics:
count    1.007913e+06
mean     1.111718e+01
std      1.284700e+02
min      1.000000e+00
25%      1.000000e+00
50%      4.000000e+00
75%      1.200000e+01
max      8.099500e+04
Name: Quantity, dtype: float64

Price statistics:
count    1.007913e+06
mean     4.074252e+00
std      5.043045e+01
min      1.000000e-03
25%      1.250000e+00
50%      2.100000e+00
75%      4.130000e+00
max      2.511109e+04
Name: Price, dtype: float64

In [47]:
# Check transactions with very high quantities

high_quantity = online_clean.nlargest(
    20, "Quantity"
)

display(
    high_quantity[
        ["Invoice", "StockCode", "Description",
         "Quantity", "InvoiceDate", "Price",
         "Customer ID", "Country"]
    ]
)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
1065882,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom
587080,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom
90857,497946,37410,BLACK AND WHITE PAISLEY FLOWER MUG,19152,2010-02-15 11:57:00,0.10,13902.0,Denmark
127166,501534,21099,SET/6 STRAWBERRY PAPER CUPS,12960,2010-03-17 13:09:00,0.10,13902.0,Denmark
127168,501534,21091,SET/6 WOODLAND PAPER PLATES,12960,2010-03-17 13:09:00,0.10,13902.0,Denmark
127169,501534,21085,SET/6 WOODLAND PAPER CUPS,12744,2010-03-17 13:09:00,0.10,13902.0,Denmark
127167,501534,21092,SET/6 STRAWBERRY PAPER PLATES,12480,2010-03-17 13:09:00,0.10,13902.0,Denmark
135027,502269,21984,PACK OF 12 PINK PAISLEY TISSUES,10000,2010-03-23 15:36:00,0.25,17940.0,United Kingdom
135028,502269,21982,PACK OF 12 SUKI TISSUES,10000,2010-03-23 15:36:00,0.25,17940.0,United Kingdom
135029,502269,21980,PACK OF 12 RED SPOTTY TISSUES,10000,2010-03-23 15:36:00,0.25,17940.0,United Kingdom
135030,502269,21981,PACK OF 12 WOODLAND TISSUES,10000,2010-03-23 15:36:00,0.25,17940.0,United Kingdom
93677,498152,85220,SMALL FAIRY CAKE FRIDGE MAGNETS,9456,2010-02-17 10:51:00,0.30,13902.0,Denmark
432176,530715,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,9360,2010-11-04 11:36:00,1.69,15838.0,United Kingdom
65091,495194,20993,JAZZ HEARTS MEMO PAD,9312,2010-01-21 15:11:00,0.10,13902.0,Denmark
298942,518505,21088,SET/6 FRUIT SALAD PAPER CUPS,7128,2010-08-09 13:10:00,0.08,14277.0,France
326847,521315,17003,BROCADE RING PURSE,7128,2010-09-03 12:01:00,0.19,15838.0,United Kingdom
358764,524174,21088,SET/6 FRUIT SALAD PAPER CUPS,7128,2010-09-27 16:30:00,0.08,13687.0,United Kingdom
298941,518505,21096,SET/6 FRUIT SALAD PAPER PLATES,7008,2010-08-09 13:10:00,0.13,14277.0,France
358763,524174,21096,SET/6 FRUIT SALAD PAPER PLATES,7008,2010-09-27 16:30:00,0.13,13687.0,United Kingdom
65090,495194,20991,JAZZ HEARTS MAGNETIC MEMO PAD,6768,2010-01-21 15:11:00,0.10,13902.0,Denmark

In [48]:
# Check transactions with very high prices

high_price = online_clean.nlargest(
    20, "Price"
)

display(
    high_price[
        ["Invoice", "StockCode", "Description",
         "Quantity", "InvoiceDate", "Price",
         "Customer ID", "Country"]
    ]
)

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
241827,512771,M,Manual,1,2010-06-17 16:53:00,25111.09,NaN,United Kingdom
517955,537632,AMAZONFEE,AMAZON FEE,1,2010-12-07 15:08:00,13541.33,NaN,United Kingdom
825443,A563185,B,Adjust bad debt,1,2011-08-12 14:50:00,11062.06,NaN,United Kingdom
135013,502263,M,Manual,1,2010-03-23 15:22:00,10953.50,12918.0,United Kingdom
135015,502265,M,Manual,1,2010-03-23 15:28:00,10953.50,NaN,United Kingdom
342147,522796,M,Manual,1,2010-09-16 15:12:00,10468.80,NaN,United Kingdom
358639,524159,M,Manual,1,2010-09-27 16:12:00,10468.80,14063.0,United Kingdom
372834,525399,M,Manual,1,2010-10-05 11:49:00,10468.80,NaN,United Kingdom
74356,496115,M,Manual,1,2010-01-29 11:04:00,8985.60,17949.0,United Kingdom
698843,551697,POST,POSTAGE,1,2011-05-03 13:46:00,8142.75,16029.0,United Kingdom
374227,525473,M,Manual,1,2010-10-05 15:16:00,7044.79,NaN,United Kingdom
129903,501766,M,Manual,1,2010-03-19 11:35:00,6958.17,15760.0,Norway
129987,501768,M,Manual,1,2010-03-19 11:45:00,6958.17,15760.0,Norway
440698,531411,AMAZONFEE,AMAZON FEE,1,2010-11-08 10:11:00,6706.71,NaN,United Kingdom
169667,505505,M,Manual,1,2010-04-22 14:09:00,5876.34,NaN,United Kingdom
159967,504639,M,Manual,1,2010-04-15 14:12:00,5843.70,NaN,United Kingdom
130004,501772,M,Manual,1,2010-03-19 11:56:00,5795.87,NaN,United Kingdom
71077,495798,ADJUST,Adjustment by john on 26/01/2010 17,1,2010-01-26 17:25:00,5117.03,NaN,United Kingdom
241728,512759,M,Manual,1,2010-06-17 15:51:00,4620.86,NaN,United Kingdom
823186,562955,DOT,DOTCOM POSTAGE,1,2011-08-11 10:14:00,4505.17,NaN,United Kingdom

In [49]:
# Check special/non-product transactions

special_codes = [
    "M",
    "AMAZONFEE",
    "POST",
    "DOT",
    "ADJUST"
]

special_transactions = online_clean[
    online_clean["StockCode"].astype(str).isin(special_codes)
]

print("Special transactions:", len(special_transactions))

display(
    special_transactions[
        ["Invoice", "StockCode", "Description",
         "Quantity", "InvoiceDate", "Price",
         "Customer ID", "Country"]
    ].head(50)
)

Special transactions: 4151

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
89,489439,POST,POSTAGE,3,2009-12-01 09:28:00,18.00,12682.0,France
126,489444,POST,POSTAGE,1,2009-12-01 09:55:00,141.00,12636.0,USA
173,489447,POST,POSTAGE,1,2009-12-01 10:10:00,130.00,12362.0,Belgium
625,489526,POST,POSTAGE,6,2009-12-01 11:50:00,18.00,12533.0,Germany
1244,489557,POST,POSTAGE,4,2009-12-01 12:52:00,18.00,12490.0,France
2379,489597,DOT,DOTCOM POSTAGE,1,2009-12-01 14:28:00,647.19,NaN,United Kingdom
2539,489600,DOT,DOTCOM POSTAGE,1,2009-12-01 14:43:00,55.96,NaN,United Kingdom
2551,489601,DOT,DOTCOM POSTAGE,1,2009-12-01 14:44:00,68.39,NaN,United Kingdom
2571,489602,DOT,DOTCOM POSTAGE,1,2009-12-01 14:45:00,59.35,NaN,United Kingdom
2619,489603,DOT,DOTCOM POSTAGE,1,2009-12-01 14:46:00,42.39,NaN,United Kingdom
2644,489604,DOT,DOTCOM POSTAGE,1,2009-12-01 14:47:00,50.87,NaN,United Kingdom
2686,489607,DOT,DOTCOM POSTAGE,1,2009-12-01 14:49:00,76.30,NaN,United Kingdom
2697,489609,M,Manual,1,2009-12-01 14:50:00,4.00,NaN,United Kingdom
2698,489609,DOT,DOTCOM POSTAGE,1,2009-12-01 14:50:00,74.61,NaN,United Kingdom
2771,489612,DOT,DOTCOM POSTAGE,1,2009-12-01 14:55:00,87.39,NaN,United Kingdom
2806,489614,DOT,DOTCOM POSTAGE,1,2009-12-01 14:56:00,80.30,NaN,United Kingdom
2820,489615,DOT,DOTCOM POSTAGE,1,2009-12-01 14:56:00,77.13,NaN,United Kingdom
2843,489616,DOT,DOTCOM POSTAGE,1,2009-12-01 14:58:00,83.74,NaN,United Kingdom
5063,489856,DOT,DOTCOM POSTAGE,1,2009-12-02 14:36:00,470.24,NaN,United Kingdom
5407,489857,DOT,DOTCOM POSTAGE,1,2009-12-02 14:43:00,775.24,NaN,United Kingdom
6406,489883,POST,POSTAGE,3,2009-12-02 16:24:00,18.00,12437.0,France
8374,490074,DOT,DOTCOM POSTAGE,1,2009-12-03 14:39:00,862.67,NaN,United Kingdom
9701,490149,DOT,DOTCOM POSTAGE,1,2009-12-04 09:43:00,922.05,NaN,United Kingdom
10279,490152,POST,POSTAGE,7,2009-12-04 10:00:00,18.00,12714.0,France
10344,490158,POST,POSTAGE,3,2009-12-04 10:47:00,18.00,12759.0,Netherlands
11193,490295,POST,POSTAGE,4,2009-12-04 13:47:00,28.00,12510.0,Spain
11310,490300,M,Manual,1,2009-12-04 14:19:00,0.85,12970.0,United Kingdom
11311,490300,M,Manual,1,2009-12-04 14:19:00,0.21,12970.0,United Kingdom
11882,490344,POST,POSTAGE,1,2009-12-04 15:53:00,18.00,NaN,United Kingdom
12475,490395,POST,POSTAGE,2,2009-12-06 10:16:00,18.00,13813.0,Germany
12508,490397,POST,POSTAGE,2,2009-12-06 10:30:00,15.00,12417.0,Belgium
12812,490458,POST,POSTAGE,4,2009-12-06 11:57:00,18.00,12583.0,France
14596,490564,POST,POSTAGE,7,2009-12-07 10:42:00,18.00,12471.0,Germany
15326,490682,POST,POSTAGE,2,2009-12-07 13:37:00,18.00,12600.0,Germany
16036,490718,POST,POSTAGE,3,2009-12-07 15:42:00,40.00,12443.0,Norway
16184,490733,POST,POSTAGE,3,2009-12-07 16:56:00,28.00,12540.0,Spain
16427,490741,DOT,DOTCOM POSTAGE,1,2009-12-07 17:56:00,862.38,NaN,United Kingdom
17266,490745,DOT,DOTCOM POSTAGE,1,2009-12-07 18:02:00,630.36,NaN,United Kingdom
17386,490760,M,Manual,1,2009-12-08 09:49:00,10.00,14295.0,United Kingdom
17617,490806,POST,POSTAGE,1,2009-12-08 12:13:00,4.00,13485.0,United Kingdom
17887,490881,M,Manual,1,2009-12-08 12:58:00,10.00,16210.0,United Kingdom
18202,490936,POST,POSTAGE,2,2009-12-08 13:56:00,28.00,12785.0,Portugal
18728,490959,POST,POSTAGE,2,2009-12-08 15:14:00,18.00,12682.0,France
19095,490963,DOT,DOTCOM POSTAGE,1,2009-12-08 15:49:00,560.87,NaN,United Kingdom
19218,490964,POST,POSTAGE,1,2009-12-08 16:09:00,15.00,14646.0,Netherlands
19542,490999,M,Manual,1,2009-12-08 17:26:00,15.95,13883.0,United Kingdom
19543,490999,M,Manual,1,2009-12-08 17:26:00,8.70,13883.0,United Kingdom
20250,491041,DOT,DOTCOM POSTAGE,1,2009-12-09 09:42:00,483.14,NaN,United Kingdom
20325,491043,DOT,DOTCOM POSTAGE,1,2009-12-09 09:51:00,660.21,NaN,United Kingdom
20826,491050,POST,POSTAGE,2,2009-12-09 10:46:00,18.00,12712.0,Germany

In [50]:
# Remove non-product transactions

special_codes = [
    "M",
    "AMAZONFEE",
    "POST",
    "DOT",
    "ADJUST"
]

before_special = len(online_clean)

online_clean = online_clean[
    ~online_clean["StockCode"].astype(str).isin(special_codes)
]

after_special = len(online_clean)

print("Rows before removing special transactions:", before_special)
print("Rows after removing special transactions:", after_special)
print("Special transactions removed:",
      before_special - after_special)

Rows before removing special transactions: 1007913
Rows after removing special transactions: 1003762
Special transactions removed: 4151

In [51]:
# Final cleaning validation

print("Final dataset shape:", online_clean.shape)

print("\nDuplicate rows:",
      online_clean.duplicated().sum())

print("\nMissing values:")
print(online_clean.isnull().sum())

print("\nQuantity:")
print("Minimum:", online_clean["Quantity"].min())
print("Negative:", (online_clean["Quantity"] < 0).sum())
print("Zero:", (online_clean["Quantity"] == 0).sum())

print("\nPrice:")
print("Minimum:", online_clean["Price"].min())
print("Negative:", (online_clean["Price"] < 0).sum())
print("Zero:", (online_clean["Price"] == 0).sum())

Final dataset shape: (1003762, 8)

Duplicate rows: 0

Missing values:
Invoice             0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
Price               0
Customer ID    226869
Country             0
dtype: int64

Quantity:
Minimum: 1
Negative: 0
Zero: 0

Price:
Minimum: 0.001
Negative: 0
Zero: 0

In [52]:
online_clean.to_csv(
    "../data/processed/online_retail_clean.csv",
    index=False
)